name: Image Builder-1
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    paths:
      - 'ACTIONS-EKS-PIPE-DEPLOY/backend/**'
jobs:
  step_a:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: folder move
        uses: actions/checkout@v4
        with:
          sparse-checkout: ACTIONS-EKS-PIPE-DEPLOY
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install pre
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/backend
        run: |
          npm install
      - name: Check
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/backend
        run: |
            node server.js &
            sleep 5
            node test.js
  step_b:
    if: github.actor != 'github-actions[bot]'
    needs: step_a
    runs-on: ubuntu-latest
    steps:
      - name: Folder copy
        uses: actions/checkout@v4
        with:
          sparse-checkout: ACTIONS-EKS-PIPE-DEPLOY
      - name: Read version
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/backend
        run: |
          VERSION=$(cat up_cmg_versions.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Docker image creation
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/backend
        run: |
          docker build -t 384235570959.dkr.ecr.us-east-1.amazonaws.com/pipeline/eks:backendv${{ env.VERSION }} .
      - name: Push to ECR
        if: success()
        run: |
          sudo snap install aws-cli --classic
          aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }} && aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}  && aws configure set default.region "us-east-1" && aws configure set default.output "json"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 384235570959.dkr.ecr.us-east-1.amazonaws.com
          docker push 384235570959.dkr.ecr.us-east-1.amazonaws.com/pipeline/eks:backendv${{ env.VERSION }}
      - name: Send Email before deployment
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}
            subject: "Approval Required"
            to: thenihanth@gmail.com
            from: GitHub Actions
            body: "Hi Team,
                   We have developed backend new version backendv${{ env.VERSION }} and pushed the image to ECR, 
                   Kindly check the image version and deploy it in pods.
                   
                   
                   Thank you
                   PIPELINE-TEAM"
      # - name: Install dependencies
      #   if: success()
      #   run: |
      #     sudo snap install kubectl --classic   
      #     curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp && sudo mv /tmp/eksctl /usr/local/bin/   
      #     aws eks update-kubeconfig --name serious-funk-crab
      #     kubectl set image deployment/back backend=384235570959.dkr.ecr.us-east-1.amazonaws.com/pipeline/eks:backendv${{ env.VERSION }}
      - name: update version
        if: success()
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/backend
        run: |
          VERSION=$(cat up_cmg_versions.txt)
          NEW_VERSION=$((VERSION + 1))
          echo $NEW_VERSION > up_cmg_versions.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: push to github
        if: success()
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/backend
        run: |
          git config --global user.name "Nihanth-sai"
          git config --global user.email "bandaru.nihanthsai@hcltech.com"
          git add up_cmg_versions.txt
          git commit -m "Update version to  $NEW_VERSION"
          git pull origin main --rebase
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          
        

