name: Image Builder
on:
  workflow_dispatch:
  push:
    paths:
      - 'ACTIONS-EKS-PIPE-DEPLOY/frontend/**'
jobs:
  step_a:
    runs-on: ubuntu-latest
    steps:
      - name: folder move
        uses: actions/checkout@v4
        with:
          sparse-checkout: ACTIONS-EKS-PIPE-DEPLOY
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install pre
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/frontend
        run: |
          npm install
          npm run build
           
