name: Image Builder
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    paths:
      - 'ACTIONS-EKS-PIPE-DEPLOY/frontend/**'
jobs:
  step_a:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: folder move
        uses: actions/checkout@v4
        with:
          sparse-checkout: ACTIONS-EKS-PIPE-DEPLOY
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install pre
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/frontend
        run: |
          npm install
          npm run build
  step_b:
    if: github.actor != 'github-actions[bot]'
    needs: step_a
    runs-on: ubuntu-latest
    steps:
      - name: Folder copy
        uses: actions/checkout@v4
        with:
          sparse-checkout: ACTIONS-EKS-PIPE-DEPLOY
      - name: Read version
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/frontend
        run: |
          VERSION=$(cat up_cmg_versions.txt)
          echo "$VERSION" >> $GITHUB_ENV
      - name: Docker image creation
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/frontend
        run: |
          docker build -t nihanthsai/nihan:action-frontend-v${{ env.VERSION }} .
          echo ${{ env.VERSION }}
      - name: update version
        if: success()
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/frontend
        run: |
          VERSION=$(cat up_cmg_versions.txt)
          NEW_VERSION=$((VERSION + 1))
          echo $NEW_VERSION > up_cmg_versions.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: push to github
        if: success()
        working-directory: ACTIONS-EKS-PIPE-DEPLOY/frontend
        run: |
          git config --global user.name "Nihanth-sai"
          git config --global user.email "bandaru.nihanthsai@hcltech.com"
          git add up_cmg_versions.txt
          git commit -m "Update version to  $NEW_VERSION"
          git pull origin main --rebase
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          